### ISSUE TITLE
 Change apt sources mirror

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#1]
http://cloudfront.debian.net/  has been intermittently giving us issues on aws builds for a while. This also presents us with a good reason to default to a consistent source across all our providers.

Make all builds (Debian based) use the official Debian mirrors at debian.org. This ought to be the most stable choice.

I'm calling this an enhancement because it solves an external problem.

https://bitbucket.org/terminal_labs/rambo/issues/2/change-apt-sources-mirror

**Comment by verhulstm** [comment]
I see that this problem is still occurring on aws

**Comment by verhulstm** [comment]
We can pull down stable trusted source files from our new public repo

https://github.com/terminal-labs/apt-sources

**Comment by verhulstm** [comment]
this command should do it

wget -O /etc/apt/sources.list https://raw.githubusercontent.com/terminal-labs/apt-sources/master/ubuntu-1404/official/sources.list

**Comment by verhulstm** [comment]
pr  is up
