### ISSUE TITLE
Allow custom placement of .tmp dir

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#113]
Normally a .tmp dir is placed in the cwd. There may be a time when you want to set this manually though, so allow it.

**Comment by alan-cugler** [comment]
Do you want this to be a setting they change in the app.py file before running "rambo up," or a menu option that pops up during the setup process when running "rambo up?"

**Comment by nixjdm** [comment]
This needs to be changeable by environment variable (this may already work), by the [CLI as an option on the command `rambo` just like this](https://github.com/terminal-labs/rambo/blob/master/rambo/cli.py#L37-L39), and available to the Python API to vagrant up, ssh, and destroy like [this](https://github.com/terminal-labs/rambo/blob/master/rambo/app.py#L84).
