### ISSUE TITLE
Move provisioning to core Vagrantfile

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#126]
There is a big chunk of the Vagrantfiles in each provider that is nearly identical:
https://github.com/terminal-labs/rambo/blob/master/rambo/vagrant_resources/vagrant/Vagrantfile.virtualbox#L107-L140
https://github.com/terminal-labs/rambo/blob/master/rambo/vagrant_resources/vagrant/Vagrantfile.lxc#L37-L71
etc.

These should all be moved into the the [core vagrant](https://github.com/terminal-labs/rambo/blob/master/rambo/vagrant_resources/vagrant/core) file. The couple of lines of embedded bash that is different should be constructed from knowing which provider was chosen.

**Comment by alan-cugler** [comment]
currently working on this issue. I have pulled the  code from both Vagrantfile.virtualbox & Vagrantfile.lxc. I dumped it into the core file. I added in a if statement in the same format as an if statement below it like this:
`if [ -d "/vagrant/auth/licenses/" ]; then cp -a /vagrant/auth/licenses/. /vagrant/salt_resources/states/files/licenses/; fi`

my added if statement looks like this ( not a finished product, just trying to get the code to work):
`if [ target == "virtualbox" ]; then cp /vagrant/salt_resources/minions/minion.virtualbox /etc/salt/minion; fi` 
`if [ target != "virtualbox" ]; then cp /vagrant/salt_resources/minions/minion.lxc /etc/salt/minion; fi`

My error after running `rambo up` is:

```virtualboxvirtualbox/home/mercury/Desktop/alan_work/rambo_stuff/rambo/rambo/vagrant_resources/vagrant/core:89:in `block in <top (required)>': uninitialized constant PROVISION_SALT_CMD (NameError)
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/v2/loader.rb:37:in `load'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:125:in `block (2 levels) in load'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `each'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `block in load'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `each'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `load'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/vagrantfile.rb:28:in `initialize'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `new'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `vagrantfile'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:556:in `host'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:214:in `block in action_runner'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:33:in `run'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:543:in `hook'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:792:in `unload'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `ensure in <main>'
from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `<main>'```


line 89 and the surrounding code looks like this:
 ```  config.vm.provision "shell",                                                                                  
      inline: $pre_salt,                                                                                          
      keep_color: true                                                                                            
    config.vm.provision "shell",                                                                                  
      inline: PROVISION_SALT_CMD,                                                                                 
      keep_color: true                                                                                            
  end```

**Comment by nixjdm** [comment]
This is the hard part of this ticket. The global var $pre_salt needs to be rendered with a variable. This can probably be accomplished in a handful of ways. As your code is now (I think) it looks like you're trying to use the Ruby `target` var, as typed out in a string, but that is failing because it is just rendered as a string, not understood as a var.

Some possibly helpful links:
https://www.vagrantup.com/docs/provisioning/shell.html#inline-scripts
https://stackoverflow.com/questions/33344187/does-double-less-than-minus-sign-mean-anything-in-ruby
