### ISSUE TITLE
Replace vagrant ssh os.system call

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#139]
https://github.com/terminal-labs/rambo/blob/master/rambo/app.py#L139

This line should probably be replaced with a subprocess command, and common exceptions should be handled. If we end up keeping os.system I want a decent explanation first for why that's acceptable long term. ATM it seems like technical debt.

**Comment by verhulstm** [comment]
I don't think you can use subprocess in this context.

os.system is only used for the "rambo ssh" command. The ssh command needs a different call API in order to take over the terminal in an interactive way. I tried subprocess first and did not find a way to make an interactive session.

**Comment by nixjdm** [comment]
You might be right.

**Comment by nixjdm** [comment]
Closing in favor of #284
