### ISSUE TITLE
we need to either support python2 or say in the docs that you must use python 3

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#142]

**Comment by nixjdm** [comment]
After discussion, we will not support Python 2. Python 3 only. Currently I don't think there is any code that won't work on Python 2, but we will not make an effort to support it going forward.

We need to note this in the docs and setup.py.

**Comment by verhulstm** [comment]
can we close this one?

**Comment by nixjdm** [comment]
Not yet. Docs are not revised.
