### ISSUE TITLE
digitalocean non-graceful exit & non-informative error from failed rambo spin up

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/rambo#159]
If you run `rambo up -p digitalocean` without having your token set, you receive an unhelpful error, and the terminal sits without exiting the spin up attempt. The error looks as follows:

```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: digital_ocean>
Line number: 9
Message: TypeError: no implicit conversion of nil into String
```
[required] exit gracefully to idle terminal,
[required] more informative error feedback,
[optional] run rambo destroy automatically,
[optional] reference which documentation needed for review to fix this error,
[optional] specify what file and/or lines needing modification.

**Comment by nixjdm** [comment]
Closing this in favor of #245
