### ISSUE TITLE
need to add "dkms to list of deps needed to install

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#164]

**Comment by verhulstm** [comment]
If we are drawing a line in the sand that a user is responsible for getting vbox fully installed. then we don't need to explain how to install dkms in the main docs. 

Maybe make a nice blog post about how to install vbox?

**Comment by nixjdm** [comment]
Yeah maybe a blog post, but yes, we'll not explain this in our docs here, so I'm closing this to clean up.
