### ISSUE TITLE
we need a way to load lastpass auth keys into grains 

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#184]
we can load them in the grains file. this is very easy and works well but it would be very easy to accidentally add the file with the keys into the git repo.

I want to find a way to load the data into grains and list the files that does the loading in .gitingore so we don't check the keys into git

**Comment by nixjdm** [comment]
Loading from the auth/keys dir should be easy enough. Also, this sounds like a good use case for giving the CLI the ability to pass arbitrary grains in which sounds easy too.

**Comment by verhulstm** [comment]
Take a look at this

https://github.com/salt-formulas/salt-formula-salt/blob/master/salt/minion/grains.sls

It seem that salt does not support multiple grains files so we need to take the main grain file and any other (like the secure one form the auth dir) and merge it into the main file.
