### ISSUE TITLE
give deescalated user ssh keys to remote repo server

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#188]
Right now the ssh keys needed to not have interact with a remote server are not shared from the root user to the deescalated user. We need a passive way to allow this, probably controlled and set up by vagrant. Salt should be able to use this as well as the sharing being persistent in a vagrant ssh.

**Comment by verhulstm** [comment]
I just ran into this issue again.

Can we add an ssh dir into the auth dir that has the ssh keys the user wants to use in it? 

Then, rambo have place those files in /home/vagrant/.ssh

**Comment by verhulstm** [comment]
you can manually copy in the ssh keys by running these commands:

rambo scp ~/.ssh/id_rsa :/home/vagrant/.ssh/id_rsa
rambo scp ~/.ssh/id_rsa.pub :/home/vagrant/.ssh/id_rsa.pub
