### ISSUE TITLE
docs for vpn salt states

### ISSUE THREAD

**Issue by smitty42** [terminal-labs/rambo#207]

**Comment by smitty42** [comment]
User needs to edit base.conf

User needs to generate client keys and config files.

**Comment by nixjdm** [comment]
Ref #17

**Comment by verhulstm** [comment]
can we close this ticket? we moved all the states out to their own repos.

**Comment by nixjdm** [comment]
Let's port it first, but yes, this and most / all of the other salt stack issues. see #222
