### ISSUE TITLE
Improve install.md

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#209]
Some people may be tripped up if they jump into install.md and don't know how to install rambo with pip. We say it in the readme, but it should be duplicated in install.

**Comment by alan-cugler** [comment]
also, we provide links and a general instruction to install vagrant and virtualbox but not for any virtual environments, we should include links and general instruction for that part just like we do for everything else leading up to running rambo.

**Comment by nixjdm** [comment]
We only tell people that they should install those dependencies Vagrant / VirtualBox, not how. They have a few options and it is sometimes complicated, and out of scope, so we intentionally avoid that.

You're right though that we provide a couple some useful links. I'm cool with adding a couple links, but I don't want to provide actual instruction ourselves for how to install Conda, VirtualEnv,  VirtualEnvWrapper, alt tool, etc. It's too much out of scope.
