### ISSUE TITLE
Add support for alternative operating systems

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#21]
In the future I'd like to be able to spin up machines based off of different Operating Systems. I'm not  sure exactly what this will look like, but we could probably add some skeleton code whose only option is Debian at the moment, but can be toggled to use other OSes in the future.

**Comment by verhulstm** [comment]
which os's do you want? 

1. Ubuntu?
2. Centos?

**Comment by nixjdm** [comment]
If this Rambo gets legs in the community I foresee a desire for other standard server OSes, so yes, those two are a great place to start. I don't have an immediate need for anything though.

**Comment by verhulstm** [comment]
top 4 are
Ubuntu, Debian, CentOS, and Fedora

**Comment by verhulstm** [comment]
I want to schedule this ticket for after packaging in click for pypi

**Comment by nixjdm** [comment]
This is mainly covered by #90. I'll make separate tickets for adding in other Guest OSs
