### ISSUE TITLE
setting "GUEST_OS" env var does not work

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#215]
We should be able to set the environment var "GUEST_OS" to something like "ubuntu-1604" and have rambo spin up a box with that os.

I know this is supposed to work but it does not seem too.

**Comment by nixjdm** [comment]
The correct env var is `RAMBO_GUEST_OS`. All of the env vars that we've create are prefixed with `RAMBO_`. We also use a couple from Vagrant that do the same thing with `VAGRANT_`. See our current [list of env vars](https://github.com/terminal-labs/rambo#environment-variables) and the what [those helper functions are doing](https://github.com/terminal-labs/rambo/blob/master/rambo/vagrant/modules.rb#L35-L43).

**Comment by verhulstm** [comment]
ok cool
