### ISSUE TITLE
On syncing of auth dir or other top level contents

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#218]
when we run "createproject" we get a dir with saltstack and auth.

if i put ssh keys in this auth dir rambo cant find them.

it is looking in the auth dir in the rambo source dir.

**Comment by nixjdm** [comment]
I don't think I follow. rambo doesn't do anything with the keys there by itself, you have to add them to your keyring / source them yourself. What do you mean?

The only thing rambo does right now with the auth/ dir, is copy auth/licenses/ into the VM.

**Comment by verhulstm** [comment]
There are use cases where the secure secrets in auth need to be copied into the rambo machine. 

If a auth dir exists in the cwd it should be copied into the rambo system and be available at /vagrant/auth from inside. 

see:
https://github.com/terminal-labs/rambo/issues/249

**Comment by verhulstm** [comment]
also, when rambo copies in the auth/licenses files it looks in rambo/rambo/auth not the auth dir in the cwd. so, at this time in order for a user to transfer license files they need to edit code inside the rambo reop clone.

**Comment by verhulstm** [comment]
if you want we can make a new folder for this. maybe call it "secrets" and leave the behavior of "auth" unchanged.

**Comment by verhulstm** [comment]
any keys or config files inside "secrets/ssh" get copied into ~/.ssh in the rambo system
a grains file located at "secrets/grains/grains" gets it's contents appended into the main grains file inside the rambo system.

**Comment by nixjdm** [comment]
Ok, so this is a feature request; you want to sync more things, possibly `secrets`. The license dir not being synced correctly is a bug though. I'll make another ticket for that (on-hold though until this is sorted out).

A concern I have is that this all seems to be getting complicated to me, and thus probably more so for a theoretical user. Maybe we should refactor this a bit in an effort to try to simplify things. I'm thinking:

Have one general dir that is for syncing, and one dir that isn't. Maybe literally `synced`, and `not-synced` or `auth` still. Inside `auth` we (still) drop the provider env.sh scripts. Maybe don't have the intermediary `keys` dir. For `synced`, we literally sync the whole folder. Maybe anything that's done with that synced data should be done via Salt States if possible, and only Vagrant / bash when we can't use Salt.

E.g.:
- You want to add ssh keys to your VM's .ssh dir? Put them somewhere in `synced`, and then look for and copy them with Salt.
- You want to sync an Anaconda license file? Put them somewhere in `synced` and then look for and copy them and use them with Salt.
- You want to add pillars or more grains? Put them somewhere in `synced`. Can they be appended with Salt? I'm not sure. If not, do it with bash or something.
- Just need some other data in your cwd and you don't want it synced? Just don't put it in a synced folder. (`synced`, `saltstack`, etc)

What do you think? @smitty42 you too.

**Comment by verhulstm** [comment]
I want to sync secrets dir and have that dir be listed in .gitingore

**Comment by nixjdm** [comment]
I'm pretty sure you meant PR #328 to be a partial answer to this topic, so to keep the conversation in one place I'm answering here.

I had to go and re-familiarize myself with the syncing-related code in the Vagrantfile for a bit.

As for your PR itself, I guess that's a fine way of adding grains from a secret file. We'll just need to document that that's happening of course. It does assume we're syncing at least the `secrets/grains/grains` file, implying we have that `secrets/` dir in the working directory, which I'm fine with.

About this thread more generally, the Vagrantfile currently defaults to syncing the rambo install dir. I don't think we're using any of that though. We were using it at one time because we were loading the default salt code from there, but now we're explicitly not, so maybe we shouldn't be syncing that dir at all anymore.

The Vagrantfile also has a [toggle already to 'disable' syncing](https://github.com/terminal-labs/rambo/blob/master/rambo/Vagrantfile#L87).  Note the `else` reverts back to syncing everything in the CWD.

I think I like refactoring that a bit to just sync the cwd by default, and not the rambo install dir, and excluding the `secrets/` dir. If we do that it can look a little simpler, because we won't be looping through the provisioner dirs anymore either. Then your PR will work too.

**Comment by verhulstm** [comment]
I like "refactoring that a bit to just sync the cwd by default, and not the rambo install dir, and excluding the secrets/ dir"

**Comment by verhulstm** [comment]
this ticket is related to 

https://github.com/terminal-labs/rambo/issues/245
https://github.com/terminal-labs/rambo/issues/251
https://github.com/terminal-labs/rambo/pull/250
https://github.com/terminal-labs/rambo/issues/249
https://github.com/terminal-labs/rambo/issues/184
https://github.com/terminal-labs/rambo/issues/183
https://github.com/terminal-labs/rambo/issues/125

**Comment by verhulstm** [comment]
the secrets dir and the auth dir are related. I see auth as a "secrets dir" for api calls to providers to create  and acces vms. I see secrets as a "secrets" dir for things that are needed inside the vm.

So, i would move all licences into "secrets" 

we might be able to merge auth adn secrets. how about renaming both to secrets/internal and  secrets/external?

**Comment by verhulstm** [comment]
i also want the secrets dir (or it's future equivalent) to have a simple starter dir be emitted when a user runs "rambo createproject"

**Comment by nixjdm** [comment]
I guess the takeaways are that we want two things:

1) synced-secrets: synced and contents used to add to grains if salt is used. git-ignored
2) not-synced-secrets: git-ignored

Everything else is synced and not sensitive, so just do whatever. So the open question is simply what structure do we prefer for those two special dirs? We can probably hash that out more efficiently in person some time. Lot's of options.

**Comment by verhulstm** [comment]
another complexity is that in some case we nee the same secrets values in both synced-secrets an non-synced-secrets.

options:

1. have one secrets dir and it serves both roles (is always synced)
2. have 2 dirs and make user sometimes put the same info in 2 places
3. have 3 dirs, synced-secrets, non-synced-secrets and 'both'. the secrets in "both" are automatically  copied in the synced-secrets and non-synced-secrets

**Comment by verhulstm** [comment]
I also want rambo to look in the dir containing "rambo.conf" for secrets first, then check in ~/.rambo for a secrets dir.

**Comment by nixjdm** [comment]
I think all the syncing parts of this issue are now obsolete with the new ability to specify arbitrary sync dirs and ripping out most provisioning code, plus trying to tie up a possibly final release.
