### ISSUE TITLE
Test for python3 and warn if not running in py3

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#220]

**Comment by verhulstm** [comment]
see also https://github.com/terminal-labs/rambo/issues/161 "Test for internet connection and warn if it isn't there."

**Comment by nixjdm** [comment]
We now abort installation if Python 3+ isn't found. https://github.com/terminal-labs/rambo/blob/7a2a8ffb86072291cefd4a6b4e32d65c6ca57bba/setup.py#L2-L4
