### ISSUE TITLE
Vagrant subcommands / params don't work

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#224]
Rambo aught to pass commands that it doesn't understand, and the params that follow them, to Vagrant. This currently doesn't work.

Expected behavior: `rambo plugin list` aught to have identical output to `vagrant plugin list` after a few messages from Rambo, like `Warning -- you entered a command Rambo does not understand....`

Currently, it seems that all of these subcommands are malformed when passed to vagrant and cause vagrant to respond with the help output.

This bug has the effect that no vagrant commands can be easily ran from a rambo project. e.g. `halt`, `rsync`, etc.

**Comment by verhulstm** [comment]
kinda related to issue #225 has i can't run scp or rysnc at this time

**Comment by nixjdm** [comment]
yep. This means lots of stuff doesn't work :( thus the 'high priority' label
