### ISSUE TITLE
add in "rambo move"

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#225]
I want a command that wraps rsync to move file/dir in to and out of the target managed rambo system.

**Comment by nixjdm** [comment]
How do you want this to be different from vagrant rsync or scp?

**Comment by verhulstm** [comment]
does the scp plugin work recursively with dirs?

**Comment by nixjdm** [comment]
[Seems too](https://github.com/invernizzi/vagrant-scp#usage).

**Comment by verhulstm** [comment]
what does "rambo rsync" do that is different then "rambo scp"?

**Comment by nixjdm** [comment]
Not much. As far as I can tell, the only real differences are

1. rsync literally uses rsync, so there are a few more options than scp. i.e. rsync has more features and scp is simpler.
2. [rsync is native](https://www.vagrantup.com/docs/cli/rsync.html) and [scp is provided by a plugin](https://github.com/invernizzi/vagrant-scp).

**Comment by nixjdm** [comment]
Can we close this?

**Comment by verhulstm** [comment]
yes feel free to close it
