### ISSUE TITLE
setup.py tries to use click before installing it.

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#226]
when running "pip install -e ." I am getting this error:

      File "/home/user/Desktop/full-node/rambo/setup.py", line 1, in <module>
        import click
    ImportError: No module named 'click'

**Comment by nixjdm** [comment]
Yes. That's a bug I need to fix in setup.py. It tries to use click before installing it. I meant to fix that immediately and got side tracked, thanks for bringing it back up.
