### ISSUE TITLE
Cleanup after destroy

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#23]
I know we had issues with triggers, but we still need to clean up better after `vagrant destroy`. In particular, if you run:

```
vagrant --target=digitalocean up
vagrant destroy
vagrant --target=virtualbox up
```

you will get an error, unless you delete the `.vagrant` folder before running the second `up`.

**Comment by verhulstm** [comment]
we should handle this in the click python wrapper

**Comment by nixjdm** [comment]
Fixed in current version.
