### ISSUE TITLE
allow setting hostname

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#242]
Allow passing an option to the `up` cmd that can set the guest's hostname.

Question though: Do we want to also have this modify the VM name we use? It's not obvious to me if that's a good idea to tie to this, or make a separate feature, or not at all.

**Comment by verhulstm** [comment]
We do need the ability to set hostnames and ids separately.  In some case the hostnames must differ and still be set by a rambo user.

**Comment by nixjdm** [comment]
So do you want the default to be that when this is passed, you get the
normal vm name, and custom hostname? Just completely independent? That's
probably the easiest to understand.

**Comment by nixjdm** [comment]
Discussed. They will be completely separate, despite having the same default value.
