### ISSUE TITLE
allow setting vm_name

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#244]
The vm_name is currently set to something like `rambo-[host's hostname]-[working dir]-[much shorter hash]` and is then also used for the guest hostname. See #242. I want to be able to change this long vm name via the cli, and have this NOT change the default hostname. I.e. the hostname would still be long-form unless it is set separately.

**Comment by verhulstm** [comment]
Do we want to limit how long these names can be? it would help a user avoid some weird issues.

**Comment by nixjdm** [comment]
I'm leaning toward no. It's probably rare that someone wants something real long, and if they do, I feel like we should let them try, because they probably have a reason for wanting it.
