### ISSUE TITLE
Refactor cli vagrant passthrough

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#261]
- Create a specific command for general passthrough like --vagrant-cmd
- Duplicate `vagrant up --provision`
- Duplicate `vagrant up --destroy-on-error`
- Duplicate `vagrant ssh -c`

**Comment by verhulstm** [comment]
i dont really understand what vagrant up --destroy-on-error means. Can it detect salt errors for example?

**Comment by nixjdm** [comment]
I looked into it. destroy-on-error defaults to on, and occurs when there is a ruby error. It was added to give people to toggle this *off* so that they can better debug failing attempts at `vagrant up`
