### ISSUE TITLE
standardize existing dirs 

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#262]
rambo machines have "/vagrant" dirs in them. inflation minions don't. can we bring these closer to a std?

options:
a) add "/vagrant" to all inflation minions and put goodies there
b) create "/rambo" in all rambo and all inflation vms. rambo vms also still have "/vagrant"
c) create "/inflation" in all rambo and all inflation vms. rambo vms also still have "/vagrant"
d) create "/rambo-inflation" in all rambo and all inflation vms. rambo vms also still have "/vagrant"

I i like option "a" the best

**Comment by nixjdm** [comment]
I think this deserves an in-person group discussion, even if it's quick :)

**Comment by nixjdm** [comment]
I think I like b) `/rambo` the best. Additionally, we could change the default user to rambo instead of vagrant. :)

**Comment by verhulstm** [comment]
I am ok with b)  i dont know how much work is needed to fully convert vagrant dir into rambo dir.

changing the user name is good. it could be a somewhat hard. the vbox images would all need to be rebuilt. 

then all rambo/inflation vms would have: main user = rambo and a dir at /rambo ?

**Comment by verhulstm** [comment]
vagrant is becoming a common linux username in vms in the cloud

**Comment by nixjdm** [comment]
I'm not sold on b + changing the username, I still want to actually talk about it, but If that's the route we go,  I don't think either part would be too hard to do. We might not even need to rebuild the vagrant boxes either. We might be able to do it from within the vagrantfile.

**Comment by verhulstm** [comment]
ok, you might be able to have vagrant change the name

**Comment by nixjdm** [comment]
Obsolete
