### ISSUE TITLE
Setting up `vagrant` user only works for debian on ec2

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#273]
I don't know if there's similar problems with other providers yet.

[This block](https://github.com/terminal-labs/rambo/blob/7a5435c1bcbac8a57ed49fcc4a6dcd349694cda5/rambo/vagrant/vagrantfiles/ec2#L34-L39) is specific to swapping the 'admin' user for the 'vagrant' user. This only works for AMIs that originally use the admin user. On our whitelist that's only debian. ubuntu uses 'ubuntu' as a user. I'm fixing this along with other things in #243

**Comment by verhulstm** [comment]
yes, this is one of the many complexities in ec2 work. we might need a json file with lots of config sets in it. 

each ami can have its own user login. and ubuntu 16.04 in California might have a different login then ubunut 16.04 in Oregon.
