### ISSUE TITLE
can we have virtualbox forward 8888 to 8888 be default in addition to what we already have?

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#275]

**Comment by nixjdm** [comment]
I guess so? How many should we have? Is there a big drawback to adding more / many? I'm not sure either way.

Regardless, I think we should add an options about ports. I'll make another ticket for that.

**Comment by nixjdm** [comment]
Is this really specific to VirtualBox?

**Comment by nixjdm** [comment]
Ref #294

**Comment by verhulstm** [comment]
Q) Is this really specific to VirtualBox?
A) at first i thought it was. but now i realize it can be very general. it should work on all providers.
