### ISSUE TITLE
Port options

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#294]
I want to make an option / some options to open and forward ports. I'm not sure of the details though.

-f / --forward-ports

All of the following could work together:
- `rambo up -f 8888` to forward guest 8888 to host 8888
- `rambo up -f [8888, 9000]` to forward guest 8888 to host 8888 and guest 9000 to host 9000
- `rambo up -f {8555: 8666}` to forward guest 8555 to host 8666
- `rambo up -f {8555: 8666, 1111: 2222}` to foraward guest 8555 to host 8666 and guest 1111 to host 2222.

**Comment by verhulstm** [comment]
i think it might be cool to have this work on all providers. 

for ec2, it could reac into the vm and set a tunnel to the workstation that rambo was called from. This allows a user to access 127.0.0.1:8080 (or what ever) and connect to some service on the vm.
