### ISSUE TITLE
bug where params system can't find key

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#314]
The traceback includes:

params['guest_os'] = options.guest_os_option(params['guest_os'])
KeyError: 'guest_os'

**Comment by nixjdm** [comment]
I'm going to take a guess and say you're using the python api, and also not supplying guest_os in params. Is that right? That makes the most sense to me. If not, please provide some details:

- the actual command you ran
- the traceback, and
- the commit hash you're working from

If this is with the python api, you can avoid this by supplying the keys in `params`, though the code should be rewritten to gracefully handle non-existence of keys. Right now it assumes they exist I think.

**Comment by nixjdm** [comment]
I'll make the fix, so I'm un-assigning you guys.

**Comment by verhulstm** [comment]
"python api" - yes

how setup params?

**Comment by nixjdm** [comment]
In #315, up (and all the other functions that take params) are defined with `**params`, so you can pass the individual options in like `up(guest_os='debian-9', ram_size=234)` or store the options in a dict first and call up with expansion, like `mydict = {'guest_os':'debian-9', 'ram_size':234}; up(**mydict)`

**Comment by verhulstm** [comment]
i got it to with this:

master_params = {'guest_os':'ubuntu-1604', 'machine_type':None, 'provider':None, 'ram_size':None, 'drive_size':None, 'destroy_on_error':None}
