### ISSUE TITLE
possible bug in app.py

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#317]
It seems to be the case that line #371 in app.py is wrong:

it is:

set_vagrant_vars(params.get(vagrant_cwd), params.get(vagrant_dotfile_path))

I think it should be:
 
set_vagrant_vars(params.get('vagrant_cwd'), params.get('vagrant_dotfile_path'))

**Comment by nixjdm** [comment]
Look at my pull request from last night about #314. This is taken care of.

**Comment by verhulstm** [comment]
cool
