### ISSUE TITLE
Versions of postgres not consistent

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#32]
Our reference to postgres's path in [the minion files](https://github.com/terminal-labs/rambo/blob/master/salt_resources/minions/minion.virtualbox#L16) does not match the [version of postgres that we install](https://github.com/terminal-labs/rambo/blob/master/salt_resources/states/postgresql/init.sls#L14). The later link can simply be updated, but I'm also wondering if there's a way we can reduce the code duplication. I'm not a fan of having the same reference hardcoded in each minion file, and that isn't tied to the postgres init either.

**Comment by verhulstm** [comment]
the  hardcoded might nit be needed anymore. it has needed for pg9.3.

**Comment by nixjdm** [comment]
That would be an easy solution :)

**Comment by verhulstm** [comment]
I did some testing and it looks like this is node longer needed for pg9.4. 
I think we can close this ticket
