### ISSUE TITLE
install_postgresql state sometimes hangs.

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#34]
Sometimes while provisioning the install_postgresql state hangs indefinitely around it's apt processes. I don't know why, but I'm suspicious it's https://github.com/saltstack/salt/issues/34872. I'd like to verify that's what is going on, or find the real cause. If we can't do anything about it directly, perhaps we can figure out a way to put a timeout on that state and abort if it takes more than some time.

This is where it hangs:
```
==> default: [INFO    ] Running state [install_postgresql] at time 21:09:42.121007
==> default: [INFO    ] Executing state pkg.installed for [install_postgresql]
```
or sometimes on the next two lines
```
==> default: [INFO    ] Executing command ['apt-cache', '-q', 'policy', 'postgresql-9.4'] in directory '/root'
==> default: [INFO    ] Executing command ['apt-get', '-q', 'update'] in directory '/root'
```

**Comment by verhulstm** [comment]
committing to stick to one apt source file should fix this. most apt repos struggle with serving PostgreSQL

**Comment by verhulstm** [comment]
i think we can close this.

I have installed postgresql dozens of times recently. all installed fine.

**Comment by nixjdm** [comment]
Good. Also it's irrelevant to this repo now anyway since we moved that to https://github.com/terminal-labs/sample-states.
