### ISSUE TITLE
Adding the ability to load a locally served database dump

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#35]
What if you don't have an artifact server, or want to set one up at the moment? This is easier to quickly get development started with, and someone *cough* me *cough* can switch to using an artifact server a little later.

**Comment by verhulstm** [comment]
what protections are in place to try to prevent a user from commiting an sql dump to a repo. if we make local file referencing easy then lots of dumps will end up in the repo.

**Comment by nixjdm** [comment]
None. I can concoct a dir with hidden contents like your host_dicts dir for Docker, and that would be something. I guess I might as well.
