### ISSUE TITLE
aws issue

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#366]
rambo up -p ec2
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'dummy' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'dummy' (v0) for provider: virtualbox
    default: Downloading: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)

Progress: 0% (Rate: 0{/s, Estimated time remaining: --:--:--)

Progress: 100% (Rate: 433/s, Estimated time remaining: --:--:--)

The box you attempted to add doesn't match the provider you specified.

Provider expected: virtualbox
Provider of box: aws

**Comment by verhulstm** [comment]
The provider 'aws' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

Vagrant knows about the following providers: docker, hyperv, virtualbox, digital_ocean

**Comment by verhulstm** [comment]
might be related to this 

https://stackoverflow.com/questions/8389301/os-x-rails-failed-to-build-gem-native-extension

**Comment by nixjdm** [comment]
Does running the plugin install command fix this?

**Comment by nixjdm** [comment]
Reported privately as solved
