### ISSUE TITLE
aws gpu suppoort

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#368]
can we replace the "'t2"s here

if get_env_var_rb('machinetype')
      provider.instance_type = get_env_var_rb('machinetype')
    elsif get_env_var_rb('ramsize') == '512'
      provider.instance_type = 't2.nano'
    elsif get_env_var_rb('ramsize') == '1024'
      provider.instance_type = 't2.micro'
    elsif get_env_var_rb('ramsize') == '2048'
      provider.instance_type = 't2.small'
    elsif get_env_var_rb('ramsize') == '4096'
      provider.instance_type = 't2.medium'
    elsif get_env_var_rb('ramsize') == '8192'
      provider.instance_type = 't2.large'
    end

with

g4dn.xlarge?

maybe pass in a arg to switch to using gpus?

**Comment by nixjdm** [comment]
You can set this currently with `rambo up -p ec2 -m g4dn.xlarge`
```
  -m, --machine-type TEXT         Machine type for cloud providers. E.g.
                                  m5.medium for ec2, or s-8vcpu-32gb for
                                  digitalocean.

```
