### ISSUE TITLE
Spin up lxc in Ubuntu host

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#40]
Discussed recently with @verhulstm.

We want to allow people to use lxc on any host OS (where Rambo is installed / used), but many OSes will not run lxc out-of-the-box, or at least not with as much ease as Ubuntu. We can provide an intermediate host much like we're currently doing for Docker, and that intermediate host can run lxc.

Side note:
Since we already have this working without an intermediate host on at least Ubuntu, I'm hesitant to get rid of that functionality. Perhaps we can toggle this with an argument? If you don't need an intermediate host, why use it? So maybe we can default to using it (since it's the most stable option), but not have to. We could toggle it off. Or, better yet, just not use the intermediate option if we detect we don't need to, i.e. if we're on a compatible OS. This adds some complexity to the code, but it might be worth it. Something to chew on.

**Comment by nixjdm** [comment]
For that matter, if we ever wanted to we could spin up Docker without an intermediate host too. I'd prioritize that lowly though, and it's certainly a separate ticket.

**Comment by verhulstm** [comment]
the build-in docker provider already works in this way. Docker spins up containers on the host if possible. unless you toggle the "force vm host" option.

**Comment by nixjdm** [comment]
Cool. I didn't realize that.

**Comment by nixjdm** [comment]
Closing in favor of #135
