### ISSUE TITLE
Change box name format to be more descriptive

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#49]
Currently we have rambo-[hostname]-[uuid]. That was great a couple months ago, but now I'm actually using rambo for multiple projects I find it not specific enough.

I run `VBoxManage list runningvms`, and I see a couple rambo-nix-* boxes, and I don't know where they are. I propose changing the format to rambo-[hostname]-[dir spawned from]-uuid. I know that getting just a little longer, but it'd be way more useful to me. Note I'm *not* saying include the full path.

For example, if I make an instance from `/home/user/workspace/project/subproject`, I want the box name to be rambo-[hostname]-subproject-[uuid].

**Comment by verhulstm** [comment]
can you write out a full example name?

**Comment by nixjdm** [comment]
Sure.

What I have right now: rambo-nix-1a374c49-e63f-4e3d-b7da-e30dad2a80ae
After the change I'm proposing:

- rambo-nix-rambo-1a374c49-e63f-4e3d-b7da-e30dad2a80ae (if made in ~/workspace/rambo)
- rambo-nix-helga-1a374c49-e63f-4e3d-b7da-e30dad2a80ae (if made in ~/workspace/rambo)
- rambo-nix-tl-lektor-1a374c49-e63f-4e3d-b7da-e30dad2a80ae (if made in ~/Desktop/tl-lektor)

Though in reality the uuid portions would of course be different. This will make the human readable portion of my VM names unique and more meaningful.

**Comment by verhulstm** [comment]
I like that
