### ISSUE TITLE
update /etc/hosts for fqdn support 

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#50]
we need a salt state update the /etc/hosts file to support fqdn

the file needs to look something like this after the salt state is run:

127.0.0.1	localhost
127.0.1.1	[hostname].[domain].[tdl] [hostname]
[wan/lan ip] [hostname].[domain].[tdl] [hostname] # for each cluster member
[wan/lan ip] [hostname].[domain].[tdl] [hostname] # for each cluster member
[wan/lan ip] [hostname].[domain].[tdl] [hostname] # for each cluster member

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by nixjdm** [comment]
Could you please give me an example couple lines spelled out for me? i.e. lines related to the current box, and a line for another box?

**Comment by verhulstm** [comment]
127.0.1.1	node-master.test.local node-master
127.0.1.2	node-worker-0.test.local node-worker-0
127.0.1.3	node-worker-1.test.local node-worker-1
