### ISSUE TITLE
Short UUID portion of VM_NAME

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#52]
Now that it's the host name, it's much more easily found, and kind of obnoxious if you're actually doing work inside a Rambo VM. I want it shorter.

**Comment by verhulstm** [comment]
see:
https://stackoverflow.com/questions/14196253/generating-a-short-uuid-string-using-uuidtools-in-rails

SecureRandom.hex(5) => "98605bb20a"

**Comment by nixjdm** [comment]
Yep. I'm leaning toward urlsafe_base64 though. A little more information packed and DO should be cool with it still.

**Comment by verhulstm** [comment]
ok
