### ISSUE TITLE
write log to file

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#64]
rambo, and more extremely rambo-master, can output huge amounts of logging. I want to be able to deal with this by logging to a file.

maybe we should find some way to make this adjustable. 

Building a full cluster now can output hundreds of thousands of lines of log. 

I want some sort of boolean satisfiability solver that checks if on the order of 50-100 core critical steps pass during the build. if they all pass, the build passes/if one or more fail, the build fails. 

a nasty way to do this would be to read and process the output log. I am assuming there is a better way.

related links
https://en.wikipedia.org/wiki/Boolean_satisfiability_problem
https://gableroux.com/tips/2016/02/18/keep-saltstack-colored-output/

**Comment by nixjdm** [comment]
Checking steps might make sense for #199, but for this specifically, with #208 we now have knowledge of the exit status of the command. Is that enough? Can we close this?

Or is this ticket about general logging improvements, like rolling logs, etc?

**Comment by verhulstm** [comment]
yes. close this one :)

**Comment by nixjdm** [comment]
Coolio
