### ISSUE TITLE
Set hostname on AWS

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#66]
The hostname is set right now with Vagrant by lines like https://github.com/terminal-labs/rambo/blob/master/vagrant_resources/vagrant/Vagrantfile.virtualbox#L7 for all providers except AWS EC2. This doesn't work for aws. We still want to set the hostname of ec2 instances though. So, we need to set the hostname manually in all the places we're aware of. That is, `/etc/hosts`, `/etc/hostname`, and possible file mentioned http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html, `/etc/sysconfig/network`.

For this, among other things, we will need to resurrect https://github.com/terminal-labs/rambo/pull/63/files#diff-830a4605640e7344f47a3228f59718e3L1. Note that AWS is the only provider that should need to run this right now. I suggest first checking the hostname's value in these places, and edit it only if it needs to. Then just keep this in as default Salt code.

**Comment by verhulstm** [comment]
I got this working in inflation

https://github.com/terminal-labs/inflation/blob/7a68bb2f22785e2ea857571ed0c4e5b54c839300/inflation_resources/cluster_init/set_hostname.sls#L1
