### ISSUE TITLE
Handle tmp files better so Vagrant doesn't choke

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#68]
I use emacs. Emacs regularly creates symlinks as recovery files for files like `example.sls` as `.#example.sls`. Vagrant crokes on this. You can't run the vagrant commands while these files are present. Ideally, Vagrant should be made to not care about this, but if we can't do that, maybe we should just auto-delete them. Example error below.

```
$ vagrant rsync
==> default: Rsyncing folder: /home/joe/workspace/rambo/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/joe/workspace/rambo/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2201 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.188 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/joe/workspace/rambo/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/home/joe/workspace/rambo/" "vagrant@127.0.0.1:/vagrant"
Error: symlink has no referent: "/home/joe/workspace/rambo/salt_resources/states/postgresql/.#init.sls"
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```

**Comment by verhulstm** [comment]
see:
https://www.vagrantup.com/docs/synced-folders/rsync.html

The rsync synced folder type accepts the following options:

rsync__args (array of strings) - A list of arguments to supply to rsync. By default this is ["--verbose", "--archive", "--delete", "-z", "--copy-links"].

**Comment by nixjdm** [comment]
This was resolved a while ago by the above mentioned pr.

The fix: https://github.com/terminal-labs/rambo/blob/master/rambo/Vagrantfile#L33-L37
