### ISSUE TITLE
Multiuser Support on AWS EC2

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#71]
On AWS EC2, I'd like the ability for multiple people to spin up VMs on an organization's account without interfering so much with each other. Currently it is only really feasible for one person to do this at a time, or to share ssh keys.

**Comment by verhulstm** [comment]
I think i know how to do this. 

We set a custom key name in the aws ec2 portal. This name must also be placed in: AWS_KEYPAIR_NAME in rambo/auth/env_scripts/aws.env.sh.dist.

Also, 2 steps in the docs need to be updated. This lines:

ssh-keygen -t rsa -N '' -f "aws.pem"
xclip -sel clip < aws.pem.pub

need to be changed to:

ssh-keygen -t rsa -N '' -f "[ custome name ].pem"
xclip -sel clip < [custom name].pem.pub

**Comment by nixjdm** [comment]
This is currently fixed and described in the docs.
