### ISSUE TITLE
Switching targets can confuse Rambo

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#76]
For instance, if I vagrant up a digitalocean instance and than vagrant destroy it, and then run `vagrant --target=virtualbox up`, I get:

```
$ vagrant --target=virtualbox up
There was an issue with the request made to the DigitalOcean
API at:

Path: /v2/droplets
URI Params: {}

The response status from the API was:

Status: 401
Response: {"id"=>"unauthorized", "message"=>"Unable to authenticate you."}
```

**Comment by nixjdm** [comment]
The data that's doing this is stored somewhere in the local `.vagrant` in Rambo's root dir, though I'm not sure exactly where. Removing it the whole dir is sufficient to bypass this, though it's probably overkill.

**Comment by verhulstm** [comment]
we might be able to just  delete the  .vagrant/machines/default/virtualbox dir

but, i bet that deleting whole .vagrant is fine

**Comment by verhulstm** [comment]
this will be fixed in the click wrapper

**Comment by nixjdm** [comment]
This ticket needs to be re-verified or closed. Might not be a problem anymore.

**Comment by verhulstm** [comment]
I think we can close it. I have not seen this issue in a while.

**Comment by nixjdm** [comment]
Agreed, seems to be a non-issue anymore.
