### ISSUE TITLE
Allow setting the guest VM OS by cli arg

### ISSUE THREAD

**Issue by nixjdm** [terminal-labs/rambo#90]
Right now, the choice between debian / ubuntu is hardcoded leading to things like https://github.com/terminal-labs/rambo/pull/81/files#diff-23b6f443c01ea2efcb4f36eedfea9089. That's clearly some tech debt. We ought to be able to pass this as a cli arg.

**Comment by verhulstm** [comment]
yes, but i want to get a start on the python wrapper first.

**Comment by verhulstm** [comment]
see pr #81

**Comment by nixjdm** [comment]
Related #89

**Comment by nixjdm** [comment]
Removing beginner-friendly tag. After some more thought, because not all providers support the same list of OSs, this requires some non-trivial error handling. See #150.

**Comment by nixjdm** [comment]
Fixed by #227
