### ISSUE TITLE
try to get rambo to work with vbox on a headless servers

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#91]

**Comment by nixjdm** [comment]
Doesn't it already? I'll check sometime, but I thought my remote server was headless, in which case it's basically always worked.

**Comment by verhulstm** [comment]
in my experience it does not work reliably on a headless server. This my be because virtualbox was not installed correctly. They (virtualbox) might have fixed this, but at one time virtualbox required a head and a completely different package was installed (virtualboxheadless) if the host did not have a head.

**Comment by nixjdm** [comment]
FWIW, I'm about as sure as I can be that I have no desktop environment:

```
$ hardinfo
...
Desktop Environment		: Terminal
...
$ printenv | grep SESSION
XDG_SESSION_ID=615
$ pgrep -l "gnome|kde|mate|cinnamon|lxde|xfce|jwm"
46 kdevtmpfs
```
I have no session environment variable for a desktop environment. `XDG_SESSION_ID` is just for my ssh login session. `kdevtmpfs` is a kernel process, " k dev", not "kde" if you were curious - a red herring.

So, Rambo doesn't seem to have a problem with a computer with no desktop environment, I guess. If you ran into trouble in the past, it's probably more to do with VirtualBox anyway, which I'm not sure there's much we can do about, or we want to fight if we even can do anything. I'm kind of thinking if someone has no desktop environment, they're willing to deal with what that entails, like maybe fighting VirtualBox some more. We just shouldn't make there lives even harder if we can help it. FWIW, I feel like I commonly (but not always) have a problem installing VirtualBox, but I don't recall needing a special effort for my server.

**Comment by verhulstm** [comment]
ok, I am satisfied. We can close this ticket.

**Comment by nixjdm** [comment]
Ok, cool.
