### ISSUE TITLE
looks like we need to reorganize the files in this repo in order to include non-py file in package

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#93]
It seems the files must be in this tree structure. Only files in rambo or lower can be included in the package. In the example below "LICENSE" would not be included.

repo.
  - rambo
    - Vagrantfiles
    - vagrant_resources
  - setup.py
  - MANIFEST.in
  - LICENSE

**Comment by nixjdm** [comment]
I don't think we need to reorganize anything. At least not from what is in branch rambo-92 with setup.py at the top level. That should work either with setuptools or manifests.

https://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py

Example: https://github.com/lektor/lektor/blob/master/MANIFEST.in

**Comment by verhulstm** [comment]
In theory, yes we would not need to reorganize the files. I have not gotten this to work.

your Example: "https://github.com/lektor/lektor/blob/master/MANIFEST.in" does not seem to work either.

Try it: run pip install lektor then cd into venv/lib/python3.4/site-packages/lektor and try to find LICENSE and README.md. 

They are not packaged up and included. This is kinda bad for lektor as the LICENSE file is not given to users with the code as is expected.
