### ISSUE TITLE
Add in specific grains for github and bitbucket ssh key fingerprints 

### ISSUE THREAD

**Issue by verhulstm** [terminal-labs/rambo#99]

**Comment by nixjdm** [comment]
Right now you can set a fingerprint, and which repo hosting platform you're using. So https://github.com/terminal-labs/rambo/blob/master/salt_resources/states/git/ssh.sls is short and flexible for either bitbucket or github, or anything else.

Both bitbucket and github's fingerprints are provided and commented out in https://github.com/terminal-labs/rambo/blob/master/salt_resources/grains/grains.

Is all of that enough for your need? I might not be understanding what you're wanting here if this doesn't cover it.

**Comment by verhulstm** [comment]
sometimes in the paste i have needed both github and bitbucket keys in grains. in that case I hard coded the key i needed.

I propose, adding in the grains file:

fingerprint_bitbucket: 97:8c:1b:f2:6f:14:6b:5c:3b:ec:aa:46:46:74:7c:40 # BitBucket
fingerprint_github: 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48 # GitHub

**Comment by nixjdm** [comment]
How about we just have one fingerprint-adding state file, where we loop through however many fingerprints we need add, regardless of the reason. To do this we'd just make the fingerprint grain a list of fingerprints, so you can have a custom fingerprint, bitbucket's, github's, gitlab's, etc, just all in there. We can have the default fingerprint list just include github / bitbucket right off the bat. Similarly, we could make the hg clone and git clone states loops too. I think this will be pretty flexible.
